name: Greg's Calculator CI/CD

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code 
          uses: actions/checkout@v4
       
        - name: FTP Deploy
          uses: "SamKirkland/FTP-Deploy-Action@4.3.4"
          with: 
            server: ${{ secrets.FTP_SERVER }}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            local-dir: "./src"
            server-dir: 'public_html/'
            exclude: |
              .github
              .git
              node_modules
              .vscode
              .env
          
